db:
  src:
    dsn: "root:root@tcp(localhost:13316)/webook?charset=utf8mb4&parseTime=True&loc=Local"
  dst:
    dsn: "root:root@tcp(localhost:13316)/webook_interactive?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6380"

kafka:
  addr:
    - "localhost:9094"
grpc:
  server:
    port: 8090
    etcdAddr: "localhost:12379"
    name: "interactive"

migrator:
  http:
    addr: "localhost:8083"