// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/basic-go-project-webook/webook/comment/grpc"
	"github.com/basic-go-project-webook/webook/comment/ioc"
	"github.com/basic-go-project-webook/webook/comment/repository"
	"github.com/basic-go-project-webook/webook/comment/repository/dao"
	"github.com/basic-go-project-webook/webook/comment/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	commentDAO := dao.NewCommentDAO(db)
	commentRepository := repository.NewCommentRepository(commentDAO)
	commentService := service.NewCommentService(commentRepository)
	commentServiceServer := grpc.NewCommentServiceServer(commentService)
	server := ioc.InitGRPCXServer(commentServiceServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdPorivder = wire.NewSet(ioc.InitDB)

var serviceProvider = wire.NewSet(dao.NewCommentDAO, repository.NewCommentRepository, service.NewCommentService, grpc.NewCommentServiceServer)
