// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/basic-go-project-webook/webook/follow/grpc"
	"github.com/basic-go-project-webook/webook/follow/ioc"
	"github.com/basic-go-project-webook/webook/follow/repository"
	"github.com/basic-go-project-webook/webook/follow/repository/cache"
	"github.com/basic-go-project-webook/webook/follow/repository/dao"
	"github.com/basic-go-project-webook/webook/follow/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	followDAO := dao.NewGORMFollowDAO(db)
	cmdable := ioc.InitRedis()
	followCache := cache.NewRedisFollowCache(cmdable)
	followRepository := repository.NewFollowRepository(followDAO, followCache)
	followService := service.NewFollowService(followRepository)
	followServiceServer := grpc.NewFollowServiceServer(followService)
	server := ioc.InitGRPCXServer(followServiceServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis)

var serviceProvider = wire.NewSet(dao.NewGORMFollowDAO, cache.NewRedisFollowCache, repository.NewFollowRepository, service.NewFollowService, grpc.NewFollowServiceServer)
